id: P010764
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:26.984869
source_metadata:
  id: bdr:W1KG11869
  title: འཁོར་ལོ་དང་ཇོ་དར་གྱི་ཕན་ཡོན།
  author: ''
  volumes:
    38677d6292974272b07bd16bb6e1273d:
      image_group_id: I1KG18520
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
