id: P010764
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11869
  title: འཁོར་ལོ་དང་ཇོ་དར་གྱི་ཕན་ཡོན།
  author: ''
  volumes:
    38677d6292974272b07bd16bb6e1273d:
      image_group_id: I1KG18520
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
