id: IDCC26DFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:30:35+00:00'
last_modified: '2022-06-08T17:21:31.929332+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11869
  title: འཁོར་ལོ་དང་ཇོ་དར་གྱི་ཕན་ཡོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AAE2:
      image_group_id: I1KG18520
      title: ''
      total_pages: 86
      order: 1
      base_file: AAE2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
